### ISSUE TITLE
Crash for database if a document title is a number

### ISSUE THREAD

**Issue by melsophos** [smathot/qnotero#19]
I installed Qnotero and it crashed if an item has a title which is just a number. Here is the traceback:

```python
Traceback (most recent call last):
  File "/home/harold/.local/lib/qnotero/libqnotero/qnoteroQuery.py", line 74, in search
    self.qnotero.search(setFocus=False)		
  File "/home/harold/.local/lib/qnotero/libqnotero/qnotero.py", line 268, in search
    zoteroItemList = self.zotero.search(query)
  File "/home/harold/.local/lib/qnotero/libzotero/libzotero.py", line 349, in search
    if item.match(terms):
  File "/home/harold/.local/lib/qnotero/libzotero/zotero_item.py", line 149, in match
    term_title and term in self.title.lower():
AttributeError: 'int' object has no attribute 'lower'
```

I found the problem using a print(self.title).
I fixed it temporarily by adding a str() call around the title. An easy example is the book 1984.

**Comment by smathot** [comment]
Thanks for this! Seems easily fixed.
